### ISSUE TITLE
Synology/template_synology_hyperbackup.yaml : Crashed task are not properly detected

### ISSUE THREAD

**Issue by TrantorRWS** [lestoilfante/zabbix-integrations#4]
I got a customer NAS with "crashed" task in restore only mode.

Currently the template doesn't report this task having an issue:
https://i.postimg.cc/y89zqDf7/hyperbackup-crashed-task-zabbix.png
Apart the fact that there is no next run value, everything seems ok

After some digging I found that there is a state value available via API:
https://i.postimg.cc/kXLdhQvj/hyperbackup-crashed-task-api.png
In this case the value is "restore_only" but it should be "backupable"

We have to get the state value of task via web api and then create a trigger to check that state value is "backupable"

**Comment by lestoilfante** [comment]
You are right, `state` must be collected and linked to a new trigger for `<>"backupable"`.

At the same time, I believe we can get rid of the `status` trigger since its value is basically _informative_ about job's current processing state (suspending, discarding, wait_discard, wait_version_delete, version_deleting, preparing_version_delete, discard_failed, canceling, none, relink_waiting, relink, deleting, restore and probably more). What really matter is `last_bkp_result`, and related trigger probably needs an improved filter, not just checking for `done`.
